# Configuration for eufy-security-ws setup

# Name of the big-bear-eufy-security-ws application
# Service definitions for the big-bear-eufy-security-ws application
services:
  # Service name: big-bear-eufy-security-ws
  # The `big-bear-eufy-security-ws` service definition
  big-bear-eufy-security-ws:
    # Name of the container
    container_name: big-bear-eufy-security-ws
    # Image to be used for the container
    image: bropat/eufy-security-ws:2.0.1
    # Environment variables for the container
    environment:
      USERNAME: "[EUFY_USERNAME]"
      PASSWORD: "[EUFY_PASSWORD]"
      COUNTRY: "US"
      LANGUAGE: "en"
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local data directory to /data inside the container
      - big-bear-eufy-security-ws_data:/data
    # Network configuration
    network_mode: host
volumes:
  big-bear-eufy-security-ws_data:
    name: big-bear-eufy-security-ws_data
    driver: local
