# Configuration for plex setup

# Name of the big-bear-plex application
# Service definitions for the big-bear-plex application
services:
  # Service name: big-bear-plex
  # The `big-bear-plex` service definition
  big-bear-plex:
    # Name of the container
    container_name: big-bear-plex
    # Image to be used for the container
    image: linuxserver/plex:1.42.2
    environment:
      - PUID=1000 # specify the user id
      - PGID=1000 # specify the group id
      - TZ=Etc/UTC # specify a timezone to use.
      - VERSION=docker # Set whether to update plex or not.
      - PLEX_CLAIM= #optional Optionally you can obtain a claim token from https://plex.tv/claim and input here. Keep in mind that the claim tokens expire within 4 minutes.
    # Container restart policy
    restart: unless-stopped
    # Network mode for the container
    network_mode: host
    # Volumes to be mounted to the container
    volumes:
      - big-bear-plex_config:/config
      - big-bear-plex_tv:/tv
      - big-bear-plex_movies:/movies
volumes:
  big-bear-plex_config:
    name: big-bear-plex_config
    driver: local
  big-bear-plex_movies:
    name: big-bear-plex_movies
    driver: local
  big-bear-plex_tv:
    name: big-bear-plex_tv
    driver: local
